### ISSUE TITLE
Přidat možnost načíst konfiguraci ze souboru

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#102]
- CLI by mělo umět načíst konfigurační soubor (třeba přes `-c`/`--config`).
- Je-li nějaké nastavení zadáno v souboru i v CLI, měly by se buď spojit (třeba u `extra_pages`) nebo CLI by mělo mít přednost (třeba u `prefix`).
- Funkce `freeze` by měla brát konfiguraci jako slovník.

**Comment by nappex** [comment]
@encukou toto Issue už je také hotovo

**Comment by encukou** [comment]
Pravdu díš!
Vyřešeno v https://github.com/encukou/freezeyt/pull/109
