### ISSUE TITLE
Failing tests on Windows

### ISSUE THREAD

**Issue by adelpopelkova** [encukou/freezeyt#108]
If you clone the repository, some tests are failing on Windows probably due to different line endings. If you delete the expected outputs and create new ones, the tests will pass.

**Comment by encukou** [comment]
@adelpopelkova, s https://github.com/encukou/freezeyt/pull/106 by tohle mělo být vyřešené, je to tak?

**Comment by adelpopelkova** [comment]
Když repozitář naklonuji znovu, tak neprochází tyto dva testy:
```
tests/test_click_cli.py::test_cli_with_fixtures_output[demo_app_links_css]
tests/test_expected_output.py::test_output[demo_app_links_css]
```
Oba vyhodí Assertion Error se souborem OFL.txt
