### ISSUE TITLE
Changeable value of variable TEST_CREATE_EXPECTED_OUTPUT 

### ISSUE THREAD

**Issue by nappex** [encukou/freezeyt#143]
```python
if 'TEST_CREATE_EXPECTED_OUTPUT' in os.environ:
```

With this condition we just check if variable with that name exists. There is no any behavior changes in tests, when we set value of variable to zero

**Comment by encukou** [comment]
It would be great to document `TEST_CREATE_EXPECTED_OUTPUT` in the README as well.
