### ISSUE TITLE
Remove cssutils warnings from tests

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#154]
```
tests/test_get_links_css.py::test_links_css_static
tests/test_get_links_css.py::test_links_css_static
tests/test_get_links_css.py::test_links_css_static
tests/test_get_links_css.py::test_links_css_static
tests/test_get_links_css.py::test_links_css_all_external
tests/test_get_links_css.py::test_links_css_all_external
tests/test_get_links_css.py::test_links_css_all_external
tests/test_get_links_css.py::test_links_css_all_external
  /home/pviktori/dev/freezeyt/__venv__/lib64/python3.9/site-packages/cssutils/errorhandler.py:100: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self._logcall(msg)
```

**Comment by nappex** [comment]
@encukou @adelpopelkova @TomasBalbinder  - Thank you for review 😌 

Hello,
I'd like to ask you about your project - https://pypi.org/project/cssutils/
We choose your package cssutils for our project to get css links. Unfortunately we've received information about 'warn' method which is deprecated see the message below:
The 'warn' method is deprecated, use 'warning' instead
    self._logcall(msg)
So we decided that we'd like to make some fixes to your project to eliminate this warning message. Unfortunately we found out that links to your source of code is not available and your link on homepage does not working. 

See https://cthedot.de/cssutils/ -> there is a link to source of code https://bitbucket.org/cthedot/cssutils, but this path does not exist.
I'd like to ask you where we could found your source of code and fix it, optionally ?
Thank you for your answer and have a nice day.Best regards.
David

**Comment by adelpopelkova** [comment]
I have a feeling, that I wrote a completely different e-mail. 🙃 
___
Dear `<name>`

I'm writing to ask you about your project [cssutils](https://pypi.org/project/cssutils/).

In our project, we choose cssutils to get links from CSS. Unfortunately we are getting deprecation warnings which come from cssutils/errorhandler.py. The full output is:
```
<the warning message isn't complete it is also linking to pytest docs>
```
We'd like to get rid of the warnings. Unfortunately we weren't able to find the source code.  We checked the [documentation](https://cthedot.de/cssutils/) linked from PyPI. There we found a link to the [source code](https://bitbucket.org/cthedot/cssutils) but there is nothing there.

I'd like to ask you where can we find the source code and, possibly, fix the problem?

Thank you for your help.

Best regards
David `<maybe even your surname unless you have a signature set>`

**Comment by nappex** [comment]
Thank you, I will mix yours and mine. Summarize your english is better.

**Comment by nappex** [comment]
I've already sent the email to all maintainers of project cssutils (maintainers: c@cthedot.de and mail@peterbe.com). I've got error of christopher email account

`550 5.1.1 <c@cthedot.de>: Recipient address rejected: User unknown in virtual mailbox table`

**Comment by nappex** [comment]
I've found project [css-parser](https://github.com/ebook-utils/css-parser)

I supposed from its README that css-parser is current fork of cssutil 1.0.2 and fix some its bugs.

**Comment by nappex** [comment]
Peter's answered:


> Sorry David, I have no idea. 

> I don’t maintain it nor do I know what happened to the Bitbucket repo. 
> But if you wanted to, perhaps start a fresh new repo on GitHub or GitLab and copy the relevant LICENSE files from the raw sources. 
> Then, when it comes time to make a release to PyPI I can add you as a maintainer.

**Comment by adelpopelkova** [comment]
Actually, the css-parser you mentioned a few comments up is a fork of cssutils. They started from the last version on PyPI, and there is a commit where they renamed it. I tried to switch from cssutils to css-parser on my computer, and it has the function we use and there are no warnings after the test.
