### ISSUE TITLE
Napsat test na 2 stránky

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#2]
Napsat demo aplikaci, kde na jedné stránce je odkaz na druhou stránku.
Napsat test, který ověří že se uloží obě stránky.

**Comment by nappex** [comment]
Chápu to správně, že je nutné v demo aplikace udělat novou routu (novou stránku) a v html kódu té první stránky udělat odkaz na nově udělanou routu/stránku  ?

**Comment by encukou** [comment]
Tak nějak.
Ideálně udělat nový test (a novou aplikaci), aby byla jistota že ten původní test stále prochází.

**Comment by nappex** [comment]
zatím jsem teda udělal novou app, snažím se teď pomocí serveru dostávat endpointy i od ostatních cest z aplikace, ne pouze root cestu. Jdu na to přes klíč PATH_INFO v proměnné environ. Mohl bys mě prosím trochu nasměrovat, jak získávat body všech stránek, jestli na to jdu správně ?
současný stav vypadá takto: [https://github.com/nappex/freezeyt/tree/test_two_pages](https://github.com/nappex/freezeyt/tree/test_two_pages)

**Comment by encukou** [comment]
Nevim jestli dobre rozumim otazce.
Test by nemel ziskavat endpointy, to zaridi testovana aplikace.
Test by mel vyzkouset, ze kdyz se zavola `freeze` na aplikaci, ktera ma dve stranky, tak se ve vyslednem adresari vytvori dva soubory.

On July 10, 2020 1:23:13 PM GMT+02:00, "David Štroch" <notifications@github.com> wrote:
>zatím jsem teda udělal novou app, snažím se teď pomocí serveru dostávat
>endpointy i od ostatních cest z aplikace, ne pouze root cestu. Jdu na
>to přes klíč PATH_INFO v proměnné environ. Mohl bys mě prosím trochu
>nasměrovat, jak získávat body všech stránek, jestli na to jdu správně
>?>
>současný stav vypadá takto:
>[https://github.com/nappex/freezeyt/tree/test_two_pages](https://github.com/nappex/freezeyt/tree/test_two_pages)>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/encukou/freezeyt/issues/2#issuecomment-656624983

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nappex** [comment]
> Nevim jestli dobre rozumim otazce. Test by nemel ziskavat endpointy, to zaridi testovana aplikace. Test by mel vyzkouset, ze kdyz se zavola `freeze` na aplikaci, ktera ma dve stranky, tak se ve vyslednem adresari vytvori dva soubory.
> […](#)
> On July 10, 2020 1:23:13 PM GMT+02:00, "David Štroch" ***@***.***> wrote: zatím jsem teda udělal novou app, snažím se teď pomocí serveru dostávat endpointy i od ostatních cest z aplikace, ne pouze root cestu. Jdu na to přes klíč PATH_INFO v proměnné environ. Mohl bys mě prosím trochu nasměrovat, jak získávat body všech stránek, jestli na to jdu správně ?> současný stav vypadá takto: [[https://github.com/nappex/freezeyt/tree/test_two_pages](https://github.com/nappex/freezeyt/tree/test_two_pages)](https://github.com/nappex/freezeyt/tree/test_two_pages%5D(https://github.com/nappex/freezeyt/tree/test_two_pages))> > -- > You are receiving this because you authored the thread.> Reply to this email directly or view it on GitHub:> [#2 (comment)](https://github.com/encukou/freezeyt/issues/2#issuecomment-656624983)
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

No teď naše funkce freeze vytváří proměnnou result do které se ukládá v bitové podobě podoba stránky pod endpoitem "/". Přemýšlel jsem takto, pokud chci aby funkce freeze ukládala více stránek, tak tu další stránku musím nejprve vytvořit v `app` a potom bude v app dohledatelná a mohu si tedy i vytáhnout její obsah. Vytvořil jsem tedy další routu ve `flask app` pod endpointem "/about". Ale když si odzkouším naši funkci freeze tak proměnná `result` stále vrací pouze obsah z endpointu "/" i když vím, že někde v app je i další stránka na endpointu "/about".  Nevím tedy jak se k obsahu té další stránky dostat. Takže přemýšlím dále - když bych chtěl, aby freeze vracela obsahy všech vytvorenych endpointu a ja tento n počet obsahů budu chtít uložit do n počtu souborů tak budu potřebovat znát to n a název jednotlivých n. No a potom je iterovat a vytvářet jednotlivé soubory. Cesty jsem si našel zatím dvě.
1. je že jsem si všiml že přes slovník environ mohu přistupovat k jednotlivým endpointum pomocí klíče PATH_INFO.
2. objekt app má attribut url_map, který můžeme iterovat přes methodu iter_rules()

Jsem na dobré cestě nebo vedle jak ta jedle a takto se to vůbec neřeší ? :D

**Comment by nappex** [comment]
Ale vlastně nikdo po mě nechce přepsat také funkci freeze aby test procházel. stačí napsat test....

**Comment by Disi77** [comment]
O něco jsem se pokusila 😀 posílám PR

**Comment by Disi77** [comment]
> Tak nějak.
> Ideálně udělat nový test (a novou aplikaci), aby byla jistota že ten původní test stále prochází.

na základě komentáře k mému PR se ptám .... nový test je myšleno jako novou testovací funkci v souboru test_demo.py a novou aplikaci je myšleno novou instanci v souboru demo_app.py nebo úplně nový soubor?

**Comment by encukou** [comment]
> nikdo po mě nechce přepsat také funkci freeze aby test procházel. stačí napsat test....

Tak. Omlouvám se že to nebylo jasné. To co se snažíš řešit je trochu složitější, chci o tom na streamu povídat.
Ale je super že jsi to zkusil – teď mnohem líp rozumíš problému :)

> novou testovací funkci v souboru test_demo.py

Jo.

> a novou aplikaci je myšleno novou instanci v souboru demo_app.py nebo úplně nový soubor?

Jedno nebo druhé.

**Comment by Disi77** [comment]
Děkuji, zkusím to udělat lépe 😀

**Comment by Disi77** [comment]
> Děkuji, zkusím to udělat lépe 😀

Naprosto jsem se do toho zamotala ... takže znovu a lépe, posílám nový PR

**Comment by encukou** [comment]
Test byl přidán v https://github.com/encukou/freezeyt/pull/8
