### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by nappex** [encukou/freezeyt#209]
- [ ] consider to add new `.yaml` workflows for each task (linting, types, python-versions)
- [ ] add different platforms as `ubuntu-latest`, `macos-latest`, `windows-latest`

**Comment by encukou** [comment]
> consider to add new .yaml workflows for each task (linting, types, python-versions)

Linting and types can be done as Tox environments, in the same workflow as the usual tests.
But new platforms should use new workflow files.
