### ISSUE TITLE
Ignorovat externí odkazy

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#22]
Měl by projít test `test_external_link`.

Nejdřív bude potřeba vyřešit https://github.com/encukou/freezeyt/issues/21

**Comment by MarijaAP** [comment]
Does the solution for issue #21 resolve this issue as expected?

**Comment by encukou** [comment]
Probably not as it is, but it looks close!

**Comment by encukou** [comment]
It does now (in #24 and later changes)
