### ISSUE TITLE
Install dependecies from setup.cfg

### ISSUE THREAD

**Issue by nappex** [encukou/freezeyt#263]
Reproduce the problem:
1) make new venv
2) activate venv
3) `$ python3 -m pip install -e .[dev]` -> stdin: zsh: no matches found: .[dev]
4) `$ python3 -m pip install -e .[dev]` -> stdin: zsh: no matches found: .[dev]

`$ python3 -m pip install -e .` this command works correctly.

system info:
python: 3.9.10
shell: zsh
platform: macos 12.x

**Comment by encukou** [comment]
Oh! [] are special (and zsh is strict about it).
Try with quotes:  -e '.[dev]'
Double quotes should work too. But AFAIK only one kind works on Windows, and I'm not sure which.

On February 23, 2022 2:18:57 PM GMT+01:00, "David Štroch" ***@***.***> wrote:
>Reproduce the problem:
>1) make new venv
>2) activate venv
>3) `$ python3 -m pip install -e .[dev]` -> stdin: zsh: no matches found: .[dev]
>4) `$ python3 -m pip install -e .[dev]` -> stdin: zsh: no matches found: .[dev]
>
>
>`$ python3 -m pip install -e .` this command works correctly.
>
>system info:
>python: 3.9.10
>shell: zsh
>platform: macos 12.x
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/encukou/freezeyt/issues/263
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nappex** [comment]
Thank you very much, you are absolutely right :)
