### ISSUE TITLE
Content-type 'text/html' is different from filetype 'application/octet-stream'

### ISSUE THREAD

**Issue by jiri-one** [encukou/freezeyt#272]
I have tried to freeze my app in Falcon framework and I have some problems. The log is in attachement
[falcon freezeyt log.txt](https://github.com/encukou/freezeyt/files/8247468/falcon.freezeyt.log.txt)
.

**Comment by jiri-one** [comment]
I figured I'd freeze the blog and then add the Falcon test to freezeyt, but somehow it didn't work :).

**Comment by encukou** [comment]
There are two ways to fix this:
- Make sure the URLs should end with `/`, for example `/tema/knihy/` rather than `/tema/knihy`.
- Set `default_mimetype=text/html` (and make sure the static page server is set up to send  `/tema/knihy` as `text/html`)

**Comment by jiri-one** [comment]
fixed with `default_mimetype=text/html`
