### ISSUE TITLE
RFE: Allow per-url-pattern configuration

### ISSUE THREAD

**Issue by hroncok** [encukou/freezeyt#278]
It would be really nice if I could specify that URLs matching certain patterns would follow different configuration options. Something like:

```yaml
'*/custom.css'
  status_handlers:
      '404': ignore
```

**Comment by encukou** [comment]
This can be done in the app itself (or in custom middleware) by setting the `Freezeyt-Action` header. That's more powerful than matching URLs.

Do you have a concrete use case that we could try to simplify?

**Comment by hroncok** [comment]
I don't recall what prompted me to open this issue :( Sorry about that.

**Comment by encukou** [comment]
It's only been two years :P
