### ISSUE TITLE
Exclude tests from fixtures can be easily in conflict because of module name

### ISSUE THREAD

**Issue by nappex** [encukou/freezeyt#309]
Currently, we `pop` module name as constant `app` in `run_freezeyt_cli`. 
There is a problem with tests which we dont want to include into cycle test of all fixtures where we choosed fixtures by name `app`. We solve it by rename the `app` for eg `application` (see app_non_standard_app), but when we want exclude more test we need to rename each of that test and it means remember all custom `app` names of excluding tests, because custom name of module wont be poped by `run_freezeyt_cli`.

I have three solutions in my mind:

1. re-code whole `run_freezeyt_cli` to load module dynamically. Then we can pop module name from argument value.
2. Send argument app_dir as one level nested dirs - `app_something/app/app.py`
3. Add new attribute to apps similar to 'config_is_serializable', eg 'exclude_from_fixtures' with default value `True`

**Comment by encukou** [comment]
Another option would be to undo all imports done in a test: #311
