### ISSUE TITLE
Rename test fixture app_3pages_deep

### ISSUE THREAD

**Issue by nappex** [encukou/freezeyt#324]
I have no idea why this fixture is named as `deep`.. When I compared with app_2pages it seemed absolutely same just 3pages have one more route...

I suggest to rename just as `app_3pages`

**Comment by encukou** [comment]
`deep` is a graph theory term referring to the shape of the "site map" graph:

![image](https://user-images.githubusercontent.com/302922/199300615-566f6202-c87e-4564-a257-fdb6edf4b60a.png)

A shallow graph would link all pages from `index`:

![image](https://user-images.githubusercontent.com/302922/199300704-99a621ab-5881-4c56-a181-84eca8cea1f1.png)
