### ISSUE TITLE
Handle extra_files in config

### ISSUE THREAD

**Issue by nappex** [encukou/freezeyt#351]
Handle chars below in `url_part`

- [x] `:`
- [x] `.`
- [x] `..`
- [x] `https:` resp. `http:`
- [x] quoted comment below

**Comment by encukou** [comment]
Perhaps the URL parts should be optionally [quoted](https://docs.python.org/3/library/urllib.parse.html?highlight=urlparse#urllib.parse.unquote)
`%5c` -> `\`
`%C3%A1` -> `á`
`á` -> `á`
