### ISSUE TITLE
Warn if different URLs are saved to the same file

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#352]
Both `/` and `/index.html` are saved as `index.html`, but can be different in a dynamic app.
Links in apps designed to be frozen should be consistent, and we can warn if they're not.

Same for `x/y` and `x//y`.

**Comment by nappex** [comment]
Do we want to solve `x/y` and `x//y`? I can not test it with nowadays browsers, `curl`, `wget`. I've always get status `308` as redirect to `x/y`.

**Comment by encukou** [comment]
OK, if all tools we know of normalize `//` to `/`, let's not warn about the difference.
