### ISSUE TITLE
`werkzeug.urls.url_parse` is deprecated

### ISSUE THREAD

**Issue by nappex** [encukou/freezeyt#356]
DeprecationWarning: `werkzeug.urls.url_parse` is deprecated and will be removed in Werkzeug 3.0.
Use `urllib.parse.urlsplit` instead.

**Comment by encukou** [comment]
This was changed in #2600
The change is not always trivial, e.g. for `ascii_host` it seems we'll need to find out how to "idna decode". Perhaps we should add missing equivalents to the werkzeug docs, as we add them.

**Comment by davidism** [comment]
If you need an ASCII-only representation, you can use `werkzeug.urls.iri_to_uri` to ensure that the URL only contains ASCII characters, then call `urllib.parse.urlsplit`.
