### ISSUE TITLE
Make DEST_PATH optional

### ISSUE THREAD

**Issue by nappex** [encukou/freezeyt#367]
Does it make sense to get result of freezing not just saving as files but also as `dict` (or another suitable data structure) as input through `pipe` to be processed by computer.

Then CLI option `DEST_PATH` become optional, because result can be done in several different ways.

It does not seem as main goal of our tool, more likely as nice extra benefit.

**Comment by encukou** [comment]
`dict` is very useful for tests. But for users, we don't want to encourage saving the entire website to memory.
