### ISSUE TITLE
Zajistit, že jde nastavit "prefix" aplikace

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#40]
* [x] Spravit padající test
* [ ] Spravit dokumentační řetězce pro `url_to_filename`, `freeze`
* [x] Zkontrolovat, že `python -m freezeyt demo_app_url_for _build --prefix http://freezeyt.test/foo/` funguje a ve výstupu (v `_build/index.html`) je správná adresa
* [x] Doplnit README

**Comment by MarijaAP** [comment]
Tested ```python -m freezeyt demo_app_url_for _build --prefix http: //freezeyt.test/foo/```, it works as expected. Links are parsed correctly and the correct pages are frozen.

**Comment by adelpopelkova** [comment]
Didn't pull request https://github.com/encukou/freezeyt/pull/57 solve the last checklist item, shouldn't this issue be closed?

**Comment by nappex** [comment]
> Didn't pull request https://github.com/encukou/freezeyt/pull/57 solve the last checklist item, shouldn't this issue be closed?

I guess that Parameter url in  func url_to_filename did not correctly described
