### ISSUE TITLE
Fix formatting of messages with URLs

### ISSUE THREAD

**Issue by nappex** [encukou/freezeyt#400]
It is hard to read the content of error message for `InfiniteRedirection`

**Comment by encukou** [comment]
(See commit 46b3627)

**Comment by nappex** [comment]
[Documentation](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlsplit) described return value as [namedtuple](https://docs.python.org/3/glossary.html#term-named-tuple) instead as [SplitResult](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.SplitResult). Your code checks the type of argument as `SplitResult`. So documentation is wrong?

**Comment by encukou** [comment]
`SplitResult` is a kind of named tuple.
