### ISSUE TITLE
Převést testy s `prefix` do test_expected_output

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#55]

**Comment by nappex** [comment]
What is the best way to handle variable prefix ? How to add to dir with app ?

1. [] prefix.txt with string inside file
1. [] config.py module with constant PREFIX inside module
1. [] config.yaml with dict and key prefix

**Comment by encukou** [comment]
That's a good question; I think any will do right now but I'll mention it on the stream.

**Comment by nappex** [comment]
I just added as attribute to demo apps where is needed :/

**Comment by encukou** [comment]
Thank you!

**Comment by encukou** [comment]
Fixed in https://github.com/encukou/freezeyt/pull/61
