### ISSUE TITLE
Vylepšit renderování image v blogu

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#64]
- [ ] Přidat title, je-li nastaveno
- [ ] Opravit obrázky z externích serverů

Taky by bylo fajn to napsat trošku hezčím způsobem :)

**Comment by nappex** [comment]
What is different between html.escape and mistune.escape ? When I read docs it seems that both make same thing:

```
mistune.escape(text, quote=False, smart_amp=True)
    Replace special characters “&”, “<” and “>” to HTML-safe sequences.
```
```
 html.escape(s, quote=True)

    Convert the characters &, < and > in string s to HTML-safe sequences. Use this if you need to display text that might contain such characters in HTML. If the optional flag quote is true, the characters (") and (') are also translated; this helps for inclusion in an HTML attribute value delimited by quotes, as in <a href="...">.
```

But, it's looks like that html library solved quotes in extra. I guess that be better to use html escape for our purpose, is it right ?

**Comment by encukou** [comment]
Either is fine.

**Comment by encukou** [comment]
Fixed in https://github.com/encukou/freezeyt/pull/70
