### ISSUE TITLE
Kód v blogu není obarvený

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#67]
Pygments generuje třídu `highlight`, ale CSS používá `syntax`.

**Comment by nappex** [comment]
Já vím :D ja už psal dotaz na slack před týdnem. Z ničeho nic to přestalo fungovat, nevím jestli za to nemůže bootstrap ?

**Comment by encukou** [comment]
Jej! To se omlouvám, zapomněl jsem.
Pamatuješ si ještě, jakým příkazem jsi vytvořil CSS soubor v 6190ee56220cf8a4155d964172e8dfd8d468dedc?

**Comment by encukou** [comment]
Opraveno v #69

**Comment by nappex** [comment]
> Jej! To se omlouvám, zapomněl jsem.
> Pamatuješ si ještě, jakým příkazem jsi vytvořil CSS soubor v [6190ee5](https://github.com/encukou/freezeyt/commit/6190ee56220cf8a4155d964172e8dfd8d468dedc)?

Už jsem to našel `pygmentize -f html -S colorful -a .syntax > pygments.css`
