### ISSUE TITLE
Přidat možnost vybrat databázi/knihovnu na mimetypes

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#87]
Funkce `freeze` by měla brát nový argument, `guess_type`, což bude funkce, která se chová jako `mimetypes.guess_type` a použije se místo ní.

**Comment by encukou** [comment]
Misto argumentu tyhle veci ted mame v konfiguraci.

**Comment by encukou** [comment]
Dalsi krok bude zaridit aby se dala jednoduse pouzit databaze kterou pouziva GitHub Pages: https://github.com/jshttp/mime-db/blob/master/db.json

**Comment by nappex** [comment]
Can we make a new object which will be build from external database file?
https://docs.python.org/3/library/mimetypes.html#mimetypes.MimeTypes.read

It seems the method `read` can parse database file, then the `guess_type` will evaluate the mime type from new database....
