### ISSUE TITLE
Zařídit aby procházel test test_three_pages_deep

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#9]

**Comment by encukou** [comment]
Neřešte variantu, že podstránka odkazuje zpátky na hlavní stránku. K tomu se dostaneme příště.

**Comment by eskultety** [comment]
Podla [wsgi](https://wsgi.readthedocs.io/en/latest/definitions.html) mozes dat do `PATH_INFO` prazdny retazec a bude to prehladavat korenovy adresar aplikacie:

> PATH_INFO
>     The remainder of the request URL’s “path”, designating the virtual “location” of the request’s target within the application. This may be an empty string, if the request URL targets the application root and does not have a trailing slash.

Ale ked to spravim, tak v hlavickach je zrazu `('Location', 'http://localhost:8000/')` a vrati mi to 308 aj na index.html. Pokial `PATH_INFO` vynecham pre koren a pouzivam ho len pre "remainder path" tak to funguje ako ma. Preco to tak je?

**Comment by encukou** [comment]
Hmmm... Čím víc na to koukám, tím víc mi přijde že se Flask nechová podle specifikace :(
Je to mezní případ, protože adresa jako `http://localhost:8000` znamená `http://localhost:8000/`. Aby `PATH_INFO` pro Flask mohlo být prázdné tak je nejspíš potřeba i `SCRIPT_NAME`? Možná by stálo za to se na tuhle zvláštnost podívat podrobněji a nahlásit ji v projektu `flask` nebo `werkzeug`.

Aktuálně do `environ` dáváme jen minimum informací, tak aby fungoval Flask. Brzo se budeme muset podívat co tam má být, a začít to vyplňovat správně.

**Comment by encukou** [comment]
Vyřešeno v https://github.com/encukou/freezeyt/pull/14
